// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MSGExt
Rcpp::List MSGExt(arma::mat X, arma::mat Y, arma::mat Omega, arma::mat grplistP, arma::mat grplistQ, double lambda, double lambdaG, double grBnomThred, double convThreshold, double maxiter, arma::uword MaxNG);
RcppExport SEXP _Brilliant_MSGExt(SEXP XSEXP, SEXP YSEXP, SEXP OmegaSEXP, SEXP grplistPSEXP, SEXP grplistQSEXP, SEXP lambdaSEXP, SEXP lambdaGSEXP, SEXP grBnomThredSEXP, SEXP convThresholdSEXP, SEXP maxiterSEXP, SEXP MaxNGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type grplistP(grplistPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type grplistQ(grplistQSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambdaG(lambdaGSEXP);
    Rcpp::traits::input_parameter< double >::type grBnomThred(grBnomThredSEXP);
    Rcpp::traits::input_parameter< double >::type convThreshold(convThresholdSEXP);
    Rcpp::traits::input_parameter< double >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type MaxNG(MaxNGSEXP);
    rcpp_result_gen = Rcpp::wrap(MSGExt(X, Y, Omega, grplistP, grplistQ, lambda, lambdaG, grBnomThred, convThreshold, maxiter, MaxNG));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Brilliant_MSGExt", (DL_FUNC) &_Brilliant_MSGExt, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_Brilliant(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
